version: '0.1.1'
services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - restore-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - restore-network

networks:
  restore-network:

